const jogos = [
	{
		id: 1,
		time_casa: 'Grêmio',
		time_visitante: 'Santos',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 1,
	},
	{
		id: 2,
		time_casa: 'Atlético-MG',
		time_visitante: 'Avaí',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 1,
	},
	{
		id: 3,
		time_casa: 'Ceará',
		time_visitante: 'CSA',
		gols_casa: 4,
		gols_visitante: 0,
		rodada: 1,
	},
	{
		id: 4,
		time_casa: 'Palmeiras',
		time_visitante: 'Fortaleza',
		gols_casa: 4,
		gols_visitante: 0,
		rodada: 1,
	},
	{
		id: 5,
		time_casa: 'São Paulo',
		time_visitante: 'Botafogo',
		gols_casa: 2,
		gols_visitante: 0,
		rodada: 1,
	},
	{
		id: 6,
		time_casa: 'Flamengo',
		time_visitante: 'Cruzeiro',
		gols_casa: 3,
		gols_visitante: 1,
		rodada: 1,
	},
	{
		id: 7,
		time_casa: 'Fluminense',
		time_visitante: 'Goiás',
		gols_casa: 0,
		gols_visitante: 1,
		rodada: 1,
	},
	{
		id: 8,
		time_casa: 'Chapecoense',
		time_visitante: 'Inter-RS',
		gols_casa: 2,
		gols_visitante: 0,
		rodada: 1,
	},
	{
		id: 9,
		time_casa: 'Bahia',
		time_visitante: 'Corinthians',
		gols_casa: 3,
		gols_visitante: 2,
		rodada: 1,
	},
	{
		id: 10,
		time_casa: 'Athletico-PR',
		time_visitante: 'Vasco',
		gols_casa: 4,
		gols_visitante: 1,
		rodada: 1,
	},
	{
		id: 11,
		time_casa: 'Inter-RS',
		time_visitante: 'Flamengo',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 1,
	},
	{
		id: 12,
		time_casa: 'Cruzeiro',
		time_visitante: 'Ceará',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 2,
	},
	{
		id: 13,
		time_casa: 'Fortaleza',
		time_visitante: 'Athletico-PR',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 2,
	},
	{
		id: 14,
		time_casa: 'Corinthians',
		time_visitante: 'Chapecoense',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 2,
	},
	{
		id: 15,
		time_casa: 'Santos',
		time_visitante: 'Fluminense',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 2,
	},
	{
		id: 16,
		time_casa: 'Vasco',
		time_visitante: 'Atlético-MG',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 2,
	},
	{
		id: 17,
		time_casa: 'Botafogo',
		time_visitante: 'Bahia',
		gols_casa: 3,
		gols_visitante: 2,
		rodada: 2,
	},
	{
		id: 18,
		time_casa: 'Avaí',
		time_visitante: 'Grêmio',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 2,
	},
	{
		id: 19,
		time_casa: 'Goiás',
		time_visitante: 'São Paulo',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 2,
	},
	{
		id: 20,
		time_casa: 'CSA',
		time_visitante: 'Palmeiras',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 2,
	},
	{
		id: 21,
		time_casa: 'Grêmio',
		time_visitante: 'Fluminense',
		gols_casa: 4,
		gols_visitante: 5,
		rodada: 2,
	},
	{
		id: 22,
		time_casa: 'Cruzeiro',
		time_visitante: 'Goiás',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 3,
	},
	{
		id: 23,
		time_casa: 'Ceará',
		time_visitante: 'Atlético-MG',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 3,
	},
	{
		id: 24,
		time_casa: 'Palmeiras',
		time_visitante: 'Inter-RS',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 3,
	},
	{
		id: 25,
		time_casa: 'São Paulo',
		time_visitante: 'Flamengo',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 3,
	},
	{
		id: 26,
		time_casa: 'Vasco',
		time_visitante: 'Corinthians',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 3,
	},
	{
		id: 27,
		time_casa: 'Botafogo',
		time_visitante: 'Fortaleza',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 3,
	},
	{
		id: 28,
		time_casa: 'Chapecoense',
		time_visitante: 'Athletico-PR',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 3,
	},
	{
		id: 29,
		time_casa: 'Bahia',
		time_visitante: 'Avaí',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 3,
	},
	{
		id: 30,
		time_casa: 'CSA',
		time_visitante: 'Santos',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 3,
	},
	{
		id: 31,
		time_casa: 'Inter-RS',
		time_visitante: 'Cruzeiro',
		gols_casa: 3,
		gols_visitante: 1,
		rodada: 3,
	},
	{
		id: 32,
		time_casa: 'Atlético-MG',
		time_visitante: 'Palmeiras',
		gols_casa: 0,
		gols_visitante: 2,
		rodada: 4,
	},
	{
		id: 33,
		time_casa: 'Fortaleza',
		time_visitante: 'São Paulo',
		gols_casa: 0,
		gols_visitante: 1,
		rodada: 4,
	},
	{
		id: 34,
		time_casa: 'Corinthians',
		time_visitante: 'Grêmio',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 4,
	},
	{
		id: 35,
		time_casa: 'Santos',
		time_visitante: 'Vasco',
		gols_casa: 3,
		gols_visitante: 0,
		rodada: 4,
	},
	{
		id: 36,
		time_casa: 'Flamengo',
		time_visitante: 'Chapecoense',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 4,
	},
	{
		id: 37,
		time_casa: 'Fluminense',
		time_visitante: 'Botafogo',
		gols_casa: 0,
		gols_visitante: 1,
		rodada: 4,
	},
	{
		id: 38,
		time_casa: 'Avaí',
		time_visitante: 'CSA',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 4,
	},
	{
		id: 39,
		time_casa: 'Goiás',
		time_visitante: 'Ceará',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 4,
	},
	{
		id: 40,
		time_casa: 'Athletico-PR',
		time_visitante: 'Bahia',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 4,
	},
	{
		id: 41,
		time_casa: 'Inter-RS',
		time_visitante: 'CSA',
		gols_casa: 2,
		gols_visitante: 0,
		rodada: 4,
	},
	{
		id: 42,
		time_casa: 'Atlético-MG',
		time_visitante: 'Flamengo',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 5,
	},
	{
		id: 43,
		time_casa: 'Ceará',
		time_visitante: 'Grêmio',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 5,
	},
	{
		id: 44,
		time_casa: 'Palmeiras',
		time_visitante: 'Santos',
		gols_casa: 4,
		gols_visitante: 0,
		rodada: 5,
	},
	{
		id: 45,
		time_casa: 'São Paulo',
		time_visitante: 'Bahia',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 5,
	},
	{
		id: 46,
		time_casa: 'Vasco',
		time_visitante: 'Avaí',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 5,
	},
	{
		id: 47,
		time_casa: 'Fluminense',
		time_visitante: 'Cruzeiro',
		gols_casa: 4,
		gols_visitante: 1,
		rodada: 5,
	},
	{
		id: 48,
		time_casa: 'Chapecoense',
		time_visitante: 'Fortaleza',
		gols_casa: 1,
		gols_visitante: 3,
		rodada: 5,
	},
	{
		id: 49,
		time_casa: 'Goiás',
		time_visitante: 'Botafogo',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 5,
	},
	{
		id: 50,
		time_casa: 'Athletico-PR',
		time_visitante: 'Corinthians',
		gols_casa: 0,
		gols_visitante: 2,
		rodada: 5,
	},
	{
		id: 51,
		time_casa: 'Grêmio',
		time_visitante: 'Atlético-MG',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 5,
	},
	{
		id: 52,
		time_casa: 'Cruzeiro',
		time_visitante: 'Chapecoense',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 6,
	},
	{
		id: 53,
		time_casa: 'Fortaleza',
		time_visitante: 'Vasco',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 6,
	},
	{
		id: 54,
		time_casa: 'Corinthians',
		time_visitante: 'São Paulo',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 6,
	},
	{
		id: 55,
		time_casa: 'Santos',
		time_visitante: 'Inter-RS',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 6,
	},
	{
		id: 56,
		time_casa: 'Flamengo',
		time_visitante: 'Athletico-PR',
		gols_casa: 3,
		gols_visitante: 2,
		rodada: 6,
	},
	{
		id: 57,
		time_casa: 'Botafogo',
		time_visitante: 'Palmeiras',
		gols_casa: 0,
		gols_visitante: 1,
		rodada: 6,
	},
	{
		id: 58,
		time_casa: 'Avaí',
		time_visitante: 'Ceará',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 6,
	},
	{
		id: 59,
		time_casa: 'Bahia',
		time_visitante: 'Fluminense',
		gols_casa: 3,
		gols_visitante: 2,
		rodada: 6,
	},
	{
		id: 60,
		time_casa: 'CSA',
		time_visitante: 'Goiás',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 6,
	},
	{
		id: 61,
		time_casa: 'Inter-RS',
		time_visitante: 'Avaí',
		gols_casa: 2,
		gols_visitante: 0,
		rodada: 6,
	},
	{
		id: 62,
		time_casa: 'Atlético-MG',
		time_visitante: 'CSA',
		gols_casa: 4,
		gols_visitante: 0,
		rodada: 7,
	},
	{
		id: 63,
		time_casa: 'Ceará',
		time_visitante: 'Santos',
		gols_casa: 0,
		gols_visitante: 1,
		rodada: 7,
	},
	{
		id: 64,
		time_casa: 'Corinthians',
		time_visitante: 'Goiás',
		gols_casa: 2,
		gols_visitante: 0,
		rodada: 7,
	},
	{
		id: 65,
		time_casa: 'São Paulo',
		time_visitante: 'Cruzeiro',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 7,
	},
	{
		id: 66,
		time_casa: 'Flamengo',
		time_visitante: 'Fortaleza',
		gols_casa: 2,
		gols_visitante: 0,
		rodada: 7,
	},
	{
		id: 67,
		time_casa: 'Botafogo',
		time_visitante: 'Vasco',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 7,
	},
	{
		id: 68,
		time_casa: 'Chapecoense',
		time_visitante: 'Palmeiras',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 7,
	},
	{
		id: 69,
		time_casa: 'Bahia',
		time_visitante: 'Grêmio',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 7,
	},
	{
		id: 70,
		time_casa: 'Athletico-PR',
		time_visitante: 'Fluminense',
		gols_casa: 3,
		gols_visitante: 0,
		rodada: 7,
	},
	{
		id: 71,
		time_casa: 'Grêmio',
		time_visitante: 'Fortaleza',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 7,
	},
	{
		id: 72,
		time_casa: 'Cruzeiro',
		time_visitante: 'Corinthians',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 8,
	},
	{
		id: 73,
		time_casa: 'Ceará',
		time_visitante: 'Bahia',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 8,
	},
	{
		id: 74,
		time_casa: 'Palmeiras',
		time_visitante: 'Athletico-PR',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 8,
	},
	{
		id: 75,
		time_casa: 'Santos',
		time_visitante: 'Atlético-MG',
		gols_casa: 3,
		gols_visitante: 1,
		rodada: 8,
	},
	{
		id: 76,
		time_casa: 'Vasco',
		time_visitante: 'Inter-RS',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 8,
	},
	{
		id: 77,
		time_casa: 'Fluminense',
		time_visitante: 'Flamengo',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 8,
	},
	{
		id: 78,
		time_casa: 'Avaí',
		time_visitante: 'São Paulo',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 8,
	},
	{
		id: 79,
		time_casa: 'Goiás',
		time_visitante: 'Chapecoense',
		gols_casa: 3,
		gols_visitante: 1,
		rodada: 8,
	},
	{
		id: 80,
		time_casa: 'CSA',
		time_visitante: 'Botafogo',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 8,
	},
	{
		id: 81,
		time_casa: 'Inter-RS',
		time_visitante: 'Bahia',
		gols_casa: 3,
		gols_visitante: 1,
		rodada: 8,
	},
	{
		id: 82,
		time_casa: 'Atlético-MG',
		time_visitante: 'São Paulo',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 9,
	},
	{
		id: 83,
		time_casa: 'Fortaleza',
		time_visitante: 'Cruzeiro',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 9,
	},
	{
		id: 84,
		time_casa: 'Palmeiras',
		time_visitante: 'Avaí',
		gols_casa: 2,
		gols_visitante: 0,
		rodada: 9,
	},
	{
		id: 85,
		time_casa: 'Santos',
		time_visitante: 'Corinthians',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 9,
	},
	{
		id: 86,
		time_casa: 'Vasco',
		time_visitante: 'Ceará',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 9,
	},
	{
		id: 87,
		time_casa: 'Botafogo',
		time_visitante: 'Grêmio',
		gols_casa: 0,
		gols_visitante: 1,
		rodada: 9,
	},
	{
		id: 88,
		time_casa: 'Chapecoense',
		time_visitante: 'Fluminense',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 9,
	},
	{
		id: 89,
		time_casa: 'Goiás',
		time_visitante: 'Athletico-PR',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 9,
	},
	{
		id: 90,
		time_casa: 'CSA',
		time_visitante: 'Flamengo',
		gols_casa: 0,
		gols_visitante: 2,
		rodada: 9,
	},
	{
		id: 91,
		time_casa: 'Grêmio',
		time_visitante: 'Vasco',
		gols_casa: 2,
		gols_visitante: 1,
		rodada: 9,
	},
	{
		id: 92,
		time_casa: 'Cruzeiro',
		time_visitante: 'Botafogo',
		gols_casa: 0,
		gols_visitante: 0,
		rodada: 10,
	},
	{
		id: 93,
		time_casa: 'Fortaleza',
		time_visitante: 'Avaí',
		gols_casa: 2,
		gols_visitante: 0,
		rodada: 10,
	},
	{
		id: 94,
		time_casa: 'Corinthians',
		time_visitante: 'CSA',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 10,
	},
	{
		id: 95,
		time_casa: 'São Paulo',
		time_visitante: 'Palmeiras',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 10,
	},
	{
		id: 96,
		time_casa: 'Flamengo',
		time_visitante: 'Goiás',
		gols_casa: 6,
		gols_visitante: 1,
		rodada: 10,
	},
	{
		id: 97,
		time_casa: 'Fluminense',
		time_visitante: 'Ceará',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 10,
	},
	{
		id: 98,
		time_casa: 'Chapecoense',
		time_visitante: 'Atlético-MG',
		gols_casa: 1,
		gols_visitante: 2,
		rodada: 10,
	},
	{
		id: 99,
		time_casa: 'Bahia',
		time_visitante: 'Santos',
		gols_casa: 0,
		gols_visitante: 1,
		rodada: 10,
	},
	{
		id: 100,
		time_casa: 'Athletico-PR',
		time_visitante: 'Inter-RS',
		gols_casa: 1,
		gols_visitante: 0,
		rodada: 10,
	},
	{
		id: 101,
		time_casa: 'Inter-RS',
		time_visitante: 'Grêmio',
		gols_casa: 1,
		gols_visitante: 1,
		rodada: 10,
	},
];

//console.log(dados[0]);
let tabela = [];

const calcularTabela = (nome, pontos, golsFeitos, golsSofridos) => {
	const timeExiste = tabela.find((time) => time.nome === nome);
	if (timeExiste) {
		//atualiza times
		timeExiste.jogos++,
			(timeExiste.pontos += pontos),
			(timeExiste.vitorias += pontos === 3 ? 1 : 0),
			(timeExiste.derrotas += pontos === 0 ? 1 : 0),
			(timeExiste.empates += pontos === 1 ? 1 : 0),
			(timeExiste.golsFeitos += golsFeitos),
			(timeExiste.golsSofridos += golsSofridos),
			(timeExiste.saldoGols += golsFeitos - golsSofridos);
	} else {
		//insere time
		tabela.push({
			nome,
			jogos: 1,
			pontos,
			vitorias: pontos === 3 ? 1 : 0,
			derrotas: pontos === 0 ? 1 : 0,
			empates: pontos === 1 ? 1 : 0,
			golsFeitos,
			golsSofridos,
			saldoGols: golsFeitos - golsSofridos,
		});
	}
	return;
};

const criarTabela = (jogos) => {
	for (let jogo of jogos) {
		if (jogo.gols_casa === jogo.gols_visitante) {
			//empate
			calcularTabela(
				jogo.time_casa,
				1,
				jogo.gols_casa,
				jogo.gols_visitante
			);
			calcularTabela(
				jogo.time_visitante,
				1,
				jogo.gols_visitante,
				jogo.gols_casa
			);
		} else if (jogo.gols_casa > jogo.gols_visitante) {
			//time da casa venceu
			calcularTabela(
				jogo.time_casa,
				3,
				jogo.gols_casa,
				jogo.gols_visitante
			);
			calcularTabela(
				jogo.time_visitante,
				0,
				jogo.gols_visitante,
				jogo.gols_casa
			);
		} else {
			//time visitante venceu
			calcularTabela(
				jogo.time_casa,
				0,
				jogo.gols_casa,
				jogo.gols_visitante
			);
			calcularTabela(
				jogo.time_visitante,
				3,
				jogo.gols_casa,
				jogo.gols_casa
			);
		}
	}

	return;
};

const ordenaTabela = (times) => {
	const timesOrdenados = times.sort((timeA, timeB) => {
		if (timeB.pontos > timeA.pontos) return 1;
		if (timeA.pontos > timeB.pontos) return -1;
		if (timeB.vitorias > timeA.vitorias) return 1;
		if (timeA.vitorias > timeB.vitorias) return -1;
		if (timeB.saldo > timeA.saldo) return 1;
		if (timeA.saldo > timeB.saldo) return -1;
		if (timeB.golsFeitos > timeA.golsFeitos) return 1;
		if (timeA.golsFeitos > timeB.golsFeitos) return -1;
		return times.sort((a, b) => a.nome.localeCompare(b.nome));
	});
	return timesOrdenados;
};

criarTabela(jogos);
//console.log(tabela);
let tabelaOrdenada = ordenaTabela(tabela);
console.log(tabelaOrdenada);
